---

- name: adding the deadsnakes ppa
  apt_repository:
    repo: 'ppa:fkrull/deadsnakes'

- name: installing python version {{ python_version }}
  apt:
    name: "python{{ python_version }}"
    state: latest
    update_cache: yes

- name: installing python {{ python_version }} dev headers
  apt:
    name: "python{{ python_version|int }}-dev"
    state: latest
    update_cache: yes

- name: installing pip
  apt:
    name: python3-pip
    state: latest
  when: python_version >= 3

- name: installing pip
  apt:
    name: python-pip
    state: latest
  when: python_version < 3

- name: installing virtualenv
  pip:
    name: virtualenv
    state: latest
    executable: pip3
  when: python_version >= 3

- name: installing virtualenv
  pip:
    name: virtualenv
    state: latest
  when: python_version < 3
