---

- name: adding the deadsnakes ppa
  apt_repository:
    repo: 'ppa:fkrull/deadsnakes'
    update_cache: yes

- name: installing python version {{ python_version }}
  apt:
    name: "python{{ python_version }}"
    state: latest

- name: installing python {{ python_version }} dev headers
  apt:
    name: "python{{ python_version }}-dev"
    state: latest

- name: downloading pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: 0755

- name: installing pip
  command: python{{ python_version }} /tmp/get-pip.py

- name: installing virtualenv
  command: python{{ python_version }} -m pip install virtualenv
