---

- name: adding the deadsnakes ppa
  apt_repository:
    repo: 'ppa:fkrull/deadsnakes'

- name: installing python version {{ python_version }}
  apt:
    name: "python{{ python_version }}"
    state: latest
    update_cache: yes

- name: installing python {{ python_version }} dev headers
  apt:
    name: "python{{ python_version }}-dev"
    state: latest
    update_cache: yes

- name: installing pip
  command: curl https://bootstrap.pypa.io/get-pip.py | python{{ python_version }}
  when: python_version >= 3

- name: symlinking pip3 installation
  file:
    src: /usr/local/bin/pip
    dest: /usr/local/bin/pip3
    state: link
  when: python_version >= 3

- name: installing pip
  apt:
    name: python-pip
    state: latest
  when: python_version < 3

- name: installing virtualenv
  pip:
    name: virtualenv
    state: latest
    executable: pip3
  when: python_version >= 3

- name: installing virtualenv
  pip:
    name: virtualenv
    state: latest
  when: python_version < 3
